In [46]:
import sys
import numpy as np
import open3d as o3d
sys.path.insert(1, "../dataset")
from utils import readData, readPointCloud

In [47]:
ground_truth = readData("../dataset/01.txt")
ground_truth = ground_truth[:77][:]
pc = []
for i in range(1):
    file = "../dataset/01/" + str(i).zfill(6) + ".bin"
    data = readPointCloud(file)
    valid = []
    for j in range(len(data)):
        dist = np.linalg.norm(data[j][:2])
        if dist <= 50 and dist >= 10:
            valid.append(data[j])
    pc.append(valid)

In [48]:
def computePose(point_ind):
#     final_pose = []
    T = ground_truth[point_ind][:]
    T = np.reshape(T, (3,4))
    b = np.array([0,0,0,1])
    T = np.vstack ((T,b)) 
    print (T)
    return T

In [49]:
# print (ground_truth.shape)
res = computePose(76)
# print(np.shape(res[0]))

[[-1.456043e-01  3.177492e-03  9.893378e-01  7.986417e+01]
 [ 1.128566e-01  9.935207e-01  1.341856e-02 -6.121849e-01]
 [-9.828849e-01  1.136071e-01 -1.450194e-01  1.377611e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [50]:
pcd_net = o3d.geometry.PointCloud()
for i in range(76):
    if (i<9):
        pcd_text = "00000"+str(i+1)+".bin"
    else:
        pcd_text = "0000"+str(i+1)+".bin"
    pcd_ip = readPointCloud("../dataset/01/"+pcd_text)
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pcd_ip[:,:3])
#     print (np.asarray(pcd.points).shape)
    rotmat = pcd.get_rotation_matrix_from_zyx((np.pi/2,-np.pi/2,0))
    pcd = pcd.rotate(R=rotmat,center=pcd.get_center())
    pcd = pcd.transform(computePose(i))
    pcd_net += pcd
#     print (np.asarray(pcd.points))
# pcd = o3d.io.read_point_cloud(pcd_ip)
downpcd = pcd_net.voxel_down_sample(voxel_size=1)
print (type(pcd))
o3d.visualization.draw_geometries([downpcd])

[[ 1.000000e+00  9.043683e-12  2.326809e-11  1.110223e-16]
 [ 9.043683e-12  1.000000e+00  2.392370e-10  2.220446e-16]
 [ 2.326810e-11  2.392370e-10  9.999999e-01 -2.220446e-16]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[ 0.9990498  -0.00164978  0.04355194  0.05154656]
 [ 0.00176042  0.9999953  -0.00250224 -0.02424883]
 [-0.0435476   0.00257653  0.999048    1.000725  ]
 [ 0.          0.          0.          1.        ]]
[[ 0.9960495  -0.00536795  0.08863831  0.1464632 ]
 [ 0.00601022  0.9999575  -0.00698072 -0.05051622]
 [-0.08859707  0.00748588  0.9960394   1.995659  ]
 [ 0.          0.          0.          1.        ]]
[[ 0.9909271  -0.00588688  0.1342721   0.2879204 ]
 [ 0.00744818  0.9999103  -0.01112852 -0.07903059]
 [-0.1341946   0.01202763  0.990882    2.986691  ]
 [ 0.          0.          0.          1.        ]]
[[ 9.836222e-01 -3.565066e-03  1.802072e-01  4.657503e-01]
 [ 6.172884e-03  9.998841e-01 -1.391250e-02 -1.102928e-01]
 [-1.801368e-01  1.479704e-02 

[[ 3.022405e-02 -1.055359e-02  9.994875e-01  2.493112e+01]
 [ 7.695768e-02  9.970006e-01  8.200162e-03 -9.519265e-01]
 [-9.965761e-01  7.667038e-02  3.094558e-02  2.124069e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[ 7.200764e-03 -1.011089e-02  9.999230e-01  2.602348e+01]
 [ 8.125250e-02  9.966483e-01  9.492647e-03 -9.509506e-01]
 [-9.966675e-01  8.117787e-02  7.998165e-03  2.124027e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-1.358780e-02 -9.968577e-03  9.998580e-01  2.712723e+01]
 [ 8.719664e-02  9.961291e-01  1.111637e-02 -9.489508e-01]
 [-9.960984e-01  8.733528e-02 -1.266597e-02  2.121564e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-3.162964e-02 -1.065186e-02  9.994429e-01  2.824249e+01]
 [ 9.165357e-02  9.956992e-01  1.351254e-02 -9.456288e-01]
 [-9.952885e-01  9.202989e-02 -3.051732e-02  2.116969e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-4.749041e-02 -1.030237e-02  9.988186e-01  2.93702

[[-1.462604e-01  3.233250e-03  9.892409e-01  7.294957e+01]
 [ 1.105105e-01  9.937887e-01  1.309099e-02 -6.411509e-01]
 [-9.830540e-01  1.112362e-01 -1.457092e-01  1.480708e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-1.460361e-01  1.690015e-03  9.892778e-01  7.465679e+01]
 [ 1.098325e-01  9.938441e-01  1.451553e-02 -6.351425e-01]
 [-9.831634e-01  1.107746e-01 -1.453227e-01  1.455382e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-1.456358e-01  1.966691e-03  9.893363e-01  7.637583e+01]
 [ 1.116862e-01  9.936382e-01  1.446557e-02 -6.266393e-01]
 [-9.830139e-01  1.126019e-01 -1.449289e-01  1.429583e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-1.456204e-01  2.152571e-03  9.893382e-01  7.811207e+01]
 [ 1.123679e-01  9.935626e-01  1.437762e-02 -6.192733e-01]
 [-9.829385e-01  1.132635e-01 -1.449248e-01  1.403765e+01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
<class 'open3d.open3d_pybind.geometry.PointCloud'>
